export enum svgName {
  homeOutline = 'homeOutline',
  home = 'home',
  userOutline = 'userOutline',
  love = 'love',
  comment = 'comment',
  isLiked = 'isLiked',
  check = 'check',
  down = 'down',
  right = 'right',
  filter = 'filter',
  help_support = 'help_support',
  pro_account = 'pro_account',
  cancel = 'cancel',
  search = 'search',
  dashboardIcon = 'dashboardIcon',
  calendar = 'calendar',
  franceFlag = 'franceFlag',
  locker = 'locker',
  eye = 'eye',
  eye_close = 'eye_close',
}
